typo3patchescore: Refactoring, fixing

diff --git a/typo3patchescore b/typo3patchescore
--- a/typo3patchescore
+++ b/typo3patchescore
@@ -1,94 +1,88 @@
 #!/bin/bash
 
+STATE_OK=0
+STATE_WARNING=1
+STATE_CRITICAL=2
+STATE_UNKNOWN=3
+STATE_DEPENDENT=4
 
-# Execute the script on the remote server
-# ssh root@dev 'bash -s' < typo3patchescore
+critical="false"
+unknown="false"
 
+declare -a criticals
+declare -a unknowns
 
-# getLatestSecureRelease() {
-#     cat <<EOF
-# \$doc = new \DOMDocument();
-# @\$doc->loadHTMLFile("https://get.typo3.org/list/version/$1");
+declare -a latest_secure_versions
+declare -a updatable
 
-# \$elements = \$doc->getElementsByTagName("tr");
+# Find the latest core versions which include security updates
+grep_latest_secure_version() {
+php -r "                                                             \
+  \$doc = new \DOMDocument();                                        \
+  @\$doc->loadHTMLFile(\"https://get.typo3.org/list/version/$1\");   \
+  \$elements = \$doc->getElementsByTagName('tr');                    \
+  if (!is_null(\$elements)) {                                        \
+    foreach (\$elements as \$element) {                              \
+      \$nodes = \$element->childNodes;                               \
+      foreach (\$nodes as \$node) {                                  \
+        if (\$node->nodeValue === 'security') {                      \
+          foreach (\$nodes as \$node) {                              \
+            if (\$node->tagName === 'th' && !is_null(\$node)) {      \
+              echo trim(\"\$node->nodeValue\");                      \
+              return;                                                \
+            }                                                        \
+          }                                                          \
+        }                                                            \
+      }                                                              \
+    }                                                                \
+  }                                                                  \
+"                                                                    \
+| grep -Eo '([0-9]{1,}\.?){3}'
+}
 
-# if (!is_null(\$elements)) {
-#     foreach (\$elements as \$element) {
-#         \$nodes = \$element->childNodes;
-#         foreach (\$nodes as \$node) {
-#             if (\$node->nodeValue === "security") {
-#                 foreach (\$nodes as $node) {
-#                     if (\$node->tagName === "th" && !is_null(\$node)) {
-#                         echo trim("v\$node->nodeValue");
-#                         return;
-#                     }
-#                 }
-#             }
-#         }
-#     }
-# }
-# EOF
-# }
-
-# V9=$(getLatestSecureRelease "9")
-# echo $V9
-
-# Find the latest core versions
-# which include security updates
-SECURE_v7=$(php -r '$doc = new \DOMDocument();@$doc->loadHTMLFile("https://get.typo3.org/list/version/7");$elements = $doc->getElementsByTagName("tr");if (!is_null($elements)) {foreach ($elements as $element) {$nodes = $element->childNodes;foreach ($nodes as $node) {if ($node->nodeValue === "security") {foreach ($nodes as $node) {if ($node->tagName === "th" && !is_null($node)) {echo trim("v$node->nodeValue");return;}}}}}}')
-SECURE_v8=$(php -r '$doc = new \DOMDocument();@$doc->loadHTMLFile("https://get.typo3.org/list/version/8");$elements = $doc->getElementsByTagName("tr");if (!is_null($elements)) {foreach ($elements as $element) {$nodes = $element->childNodes;foreach ($nodes as $node) {if ($node->nodeValue === "security") {foreach ($nodes as $node) {if ($node->tagName === "th" && !is_null($node)) {echo trim("v$node->nodeValue");return;}}}}}}')
-SECURE_v9=$(php -r '$doc = new \DOMDocument();@$doc->loadHTMLFile("https://get.typo3.org/list/version/9");$elements = $doc->getElementsByTagName("tr");if (!is_null($elements)) {foreach ($elements as $element) {$nodes = $element->childNodes;foreach ($nodes as $node) {if ($node->nodeValue === "security") {foreach ($nodes as $node) {if ($node->tagName === "th" && !is_null($node)) {echo trim("v$node->nodeValue");return;}}}}}}')
-SECURE_v10=$(php -r '$doc = new \DOMDocument();@$doc->loadHTMLFile("https://get.typo3.org/list/version/10");$elements = $doc->getElementsByTagName("tr");if (!is_null($elements)) {foreach ($elements as $element) {$nodes = $element->childNodes;foreach ($nodes as $node) {if ($node->nodeValue === "security") {foreach ($nodes as $node) {if ($node->tagName === "th" && !is_null($node)) {echo trim("v$node->nodeValue");return;}}}}}}')
-
+is_upgratable() {
+  for n in {1..3}; do
+    [[ $(cut -d'.' -f$n <<< "${latest_secure_versions[$installed_major_version]}") -gt $(cut -d'.' -f$n <<< "$installed_version") ]] && return
+  done
+  false
+}
 
 # Find all PackageStates.php files on the server
-# -> works for conventual and Composer installations
-declare -a PACKAGE_STATES=()
-while IFS=  read -r -d $'\0'; do
-    PACKAGE_STATES+=("$REPLY")
-done < <(find /var/www -iname 'PackageStates.php' -print0)
-
-
-# Iterate over the
-# TYPO3 installations
-for i in "${PACKAGE_STATES[@]}"
-do
-    ROOT=$(echo $i | cut -d "/" -f1-4)
-
-    # COMPOSER
-    if [[ $i == *"public"* ]]; then
-        VERSION=$(node -e 'const cl = require("fs").readFileSync("'$ROOT'/composer.lock"); console.log(JSON.parse(cl).packages.find(x => x.name === "typo3/cms-core").version);')
-        MAJOR=$(echo $VERSION | head -c 2)
-
+# and iterate over the TYPO3 installations
+while read -r webroot; do
+  if [[ -L "$webroot/typo3_src" ]]; then
     # CONVENTUAL
-    else
-        VERSION=$(ls -la $ROOT | grep "typo3_src -> ../typo3" | cut -d "/" -f 3)
-        VERSION=v${VERSION//typo3_src-/}
-        MAJOR=$(echo $VERSION | head -c 2)
-    fi
+    installed_version=$(readlink -m "$webroot/typo3_src" | grep -Eo '([0-9]{1,}\.?){3}$')
+  else
+    # COMPOSER
+    installed_version=$(sed -rn "/name.*typo3\/cms-core/,/version/ {s/.*v(([0-9]{1,}\.?){3}).*/\1/p}" "$webroot/composer.lock")
+  fi
+
+  if [[ -z "$installed_version" ]]; then
+    echo "Couldn't determine installed version for: $webroot"
+    unknown="true"
+  fi
+
+  installed_major_version=${installed_version%%.*}
+
+  [[ -z "${latest_secure_versions[$installed_major_version]}" ]] && latest_secure_versions[$installed_major_version]="$(grep_latest_secure_version "$installed_major_version")"
+
+  if [[ -z "${latest_secure_versions[$installed_major_version]}" ]]; then
+    echo "Couldn't get latest secure version (v$installed_major_version)"
+    unknown="true"
+  fi
+
+  if is_upgratable; then
+    echo "$webroot:$installed_version => ${latest_secure_versions[$installed_major_version]}"
+    critical="true"
+  fi
+done < <(find /var/www -not \( -path /var/www/typo3 -prune \) -iname 'PackageStates.php' | awk -F '/typo3conf|/public' '{print $1}' | sort -u)
 
 
-    # Compare the version with
-    # the latest security release
-    case $MAJOR in
-    v7)
-        SECURE=$(node -e 'console.log(["'$VERSION'", "'"$SECURE_v7"'"].map(v => v.split(".").map(p => p.length === 1 ? `0${p}` : p).join(".")).reduce((a, b) => a >= b));')
-        $SECURE || echo "$ROOT, $VERSION: update to $SECURE_v7"
-        ;;
-    v8)
-        SECURE=$(node -e 'console.log(["'$VERSION'", "'"$SECURE_v8"'"].map(v => v.split(".").map(p => p.length === 1 ? `0${p}` : p).join(".")).reduce((a, b) => a >= b));')
-        $SECURE || echo "$ROOT, $VERSION: update to $SECURE_v8"
-        ;;
-    v9)
-        SECURE=$(node -e 'console.log(["'$VERSION'", "'"$SECURE_v9"'"].map(v => v.split(".").map(p => p.length === 1 ? `0${p}` : p).join(".")).reduce((a, b) => a >= b));')
-        $SECURE || echo "$ROOT, $VERSION: update to $SECURE_v9"
-        ;;
-    v10)
-        SECURE=$(node -e 'console.log(["'$VERSION'", "'"$SECURE_v10"'"].map(v => v.split(".").map(p => p.length === 1 ? `0${p}` : p).join(".")).reduce((a, b) => a >= b));')
-        $SECURE || echo "$ROOT, $VERSION: update to $SECURE_v10"
-        ;;
-    *)
-        echo "$ROOT - $VERSION: Unmatched"
-        ;;
-    esac
-done
+if [ "$critical" = "true" ]; then
+  exit $STATE_CRITICAL
+elif [ "$unknown" = "true" ]; then
+  exit $STATE_UNKNOWN
+else
+  exit $STATE_OK
+fi
